apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  argocd.argoproj.io/managed-by-url: {{ $.Values.argocdURL }}  
spec:
  sourceRepos: []
  sourceNamespaces: []
  destinations: []
  namespaceResourceBlacklist:
  - group: '*'
    kind: '*'