apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- if ne $isDecomissioned true }}    
  finalizers:
      - resources-finalizer.argocd.argoproj.io
  {{- end }}
  annotations:
    argocd.argoproj.io/managed-by-url: {{ $.Values.argocdURL }} 
    {{- if ne $.Values.isDecomissioned true }}
    argocd.argoproj.io/sync-options: Delete=confirm
    {{- end }}
  name: final-{{ $.Values.clusterName }}-{{ $.Values.groupName }}
  namespace: {{ $.Values.argocdNamespace }}
spec:
  project: default
  source:
    repoURL: https://github.com/helm/examples.git
    targetRevision: main
    path: charts/hello-world
    helm:
      releaseName: {{ $.Values.clusterName }}-{{ $.Values.groupName }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $.Values.clusterName }}
  syncPolicy:
    automated:
      selfHeal: true
      enabled: {{ $.Values.enableAutoSync }}
    {{- if eq $.Values.isDecomissioned true }}
      prune: true
    {{- else }}
      prune: false
    {{- end}}
    syncOptions:
      - CreateNamespace=true
---