apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: root-test-a
  name: root-test-a
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /status
      kind: Application
  project: default
  sources:
  - repoURL: https://github.com/akolpakova/demo-argocd.git
    path: template/appset
    targetRevision: HEAD
    helm:
      valueFiles:
      - $values/template/appset/dev-clusters.yaml
  - repoURL: https://github.com/akolpakova/demo-argocd.git
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true

