apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: test-root
  name: test-root
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /status
      kind: Application
  project: default
  sources:
  # - repoURL: https://github.com/akolpakova/demo-argocd.git
  #   path: template/appset
  #   targetRevision: HEAD
  #   helm:
  #     valueFiles:
  #     - $values/template/appset/production-clusters.yaml
  # - repoURL: https://github.com/akolpakova/demo-argocd.git
  #   targetRevision: HEAD
  #   ref: values
  source:
    repoURL: https://github.com/akolpakova/demo-argocd.git
    path: "test-root"
    targetRevision: HEAD
    directory:
      recurse: false
      exclude: '{test-root.yaml}'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true

