apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  generators:
  - list:
      elements:
        - url: https://kubernetes.default.svc
          prune: true
  template:
    metadata:
      name: '{{ .nameNormalized }}-deployment'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/akolpakova/demo-argocd.git
        targetRevision: test-team
        path: namespaces
      destination:
        server: '{{ .url }}'
        namespace: guestbook
  templatePatch: |
    spec:
      syncPolicy:
        automated:
          prune: {{ .prune }}