apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teams
  namespace: {{ $.Values.argocdNamespace }}  
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    argocd.argoproj.io/managed-by-url: {{ $.Values.argocdURL }}  
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $.Values.argocdNamespace }} 
  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application
  project: default
  source:
    path: projects
    repoURL: https://github.com/akolpakova/demo-argocd.git
  # sources:
  # - repoURL: https://github.com/akolpakova/demo-argocd.git
  #   path: projects
  #   targetRevision: test-team
  #   helm:
  #     valueFiles:
  #     - $values/{{"{{"}} path {{"}}"}}/config.yaml
  # - repoURL: https://github.com/akolpakova/demo-argocd.git
  #   targetRevision: test-team
  #   ref: values
  syncPolicy:
    automated:
      selfHeal: true
