apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/managed-by-url: {{ $.Values.argocdURL }}  
    argocd.argoproj.io/sync-options: Delete=false
  creationTimestamp: null
  ## DO NOT CHANGE THE NAME FOR THE PRODUCTION ARGOCD
  name: clusters{{- if eq $.Values.argocdInstanceType "development" -}}-development{{- end }}
  namespace: {{ $.Values.argocdNamespace }} 
spec:
  goTemplate: true
  generators:
  {{- range $clusterName,$clusterInfo := $.Values.clusters }}
  - git:
      directories:
      - path: 'clusters/{{ $clusterName }}'
      repoURL: https://github.com/akolpakova/demo-argocd.git
      requeueAfterSeconds: 20
      revision: {{ $.Values.targetRevision}}
      values:
        clusterName: {{ $clusterName }}
        prune: "{{ $clusterInfo.decomission }}"
  {{- end }}
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: argocd-autopilot
      name: '{{`{{ .values.clusterName }}`}}'
      namespace: {{ $.Values.argocdNamespace }} 
    spec:
      destination:
        namespace: {{ $.Values.argocdNamespace }} 
        server: https://kubernetes.default.svc
      ignoreDifferences:
      - group: argoproj.io
        jsonPointers:
        - /status
        kind: Application
      project: default
      sources:
        - repoURL: https://github.com/akolpakova/demo-argocd.git
          path: renderers/resource-kinds
          targetRevision: {{ $.Values.targetRevision}}
          helm:
            valueFiles:
            - $values/clusters/clusters-list.yaml
            - $values/argocd-{{ $.Values.argocdInstanceType }}/config.yaml
            - $values/{{`{{ .path }}`}}/config.yaml
        - repoURL: https://github.com/akolpakova/demo-argocd.git
          targetRevision: {{ $.Values.targetRevision }}
          ref: values
  templatePatch: |
    spec:
      syncPolicy:
        automated:
          prune: {{`{{ eq .values.prune "true" }}`}}
status: {}