apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"creationTimestamp":null,"finalizers":["resources-finalizer.argocd.argoproj.io"],"labels":{"app.kubernetes.io/name":"root"},"name":"root","namespace":"argocd"},"spec":{"destination":{"namespace":"argocd","server":"https://kubernetes.default.svc"},"ignoreDifferences":[{"group":"argoproj.io","jsonPointers":["/status"],"kind":"Application"}],"project":"default","sources":[{"helm":{"valueFiles":["$values/argocd-production/config.yaml","$values/clusters/clusters-list.yaml"]},"path":"renderers/clusters","repoURL":"https://github.com/akolpakova/demo-argocd.git","targetRevision":"testing-devex"},{"ref":"values","repoURL":"https://github.com/akolpakova/demo-argocd.git","targetRevision":"testing-devex"}],"syncPolicy":{"automated":{"enabled":true,"prune":true,"selfHeal":true},"syncOptions":["CreateNamespace=true"]}}}
  creationTimestamp: '2025-12-04T15:10:18Z'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  generation: 132
  labels:
    app.kubernetes.io/name: root
  name: root
  namespace: argocd
  resourceVersion: '256710'
  uid: 72e32a92-ba60-42fc-813b-7f2920025101
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/root
status:
  conditions:
    - lastTransitionTime: '2025-12-04T17:11:51Z'
      message: >-
        Failed last sync attempt to [9b78f583ad9ec20c64cebb8d6f1c373c981ce538
        9b78f583ad9ec20c64cebb8d6f1c373c981ce538]: one or more objects failed to
        apply, reason: error when patching "/dev/shm/3241259785":
        ApplicationSet.argoproj.io "clusters" is invalid: spec.generators:
        Required value (retried 5 times).
      type: SyncError
  controllerNamespace: argocd
  health:
    lastTransitionTime: '2025-12-04T15:10:19Z'
    status: Healthy
  history:
    - deployStartedAt: '2025-12-04T15:10:19Z'
      deployedAt: '2025-12-04T15:10:19Z'
      id: 0
      initiatedBy:
        automated: true
      revisions:
        - b9ac965663545d3e9b6de188a095dbb3e72a534e
      source:
        repoURL: ''
      sources:
        - directory:
            exclude: '{root.yaml}'
            jsonnet: {}
          path: .
          repoURL: https://github.com/akolpakova/demo-argocd.git
          targetRevision: testing-devex
    - deployStartedAt: '2025-12-04T15:27:02Z'
      deployedAt: '2025-12-04T15:27:02Z'
      id: 1
      initiatedBy:
        username: admin
      revisions:
        - da44adf56378388d251a619e74a5f1ece664a07e
      source:
        repoURL: ''
      sources:
        - directory:
            exclude: '{root.yaml}'
            jsonnet: {}
          path: .
          repoURL: https://github.com/akolpakova/demo-argocd.git
          targetRevision: testing-devex
    - deployStartedAt: '2025-12-04T15:30:43Z'
      deployedAt: '2025-12-04T15:30:43Z'
      id: 2
      initiatedBy:
        automated: true
      revisions:
        - ae5f12038cd53d33f48a13c90e4c6996c94fc8d1
      source:
        repoURL: ''
      sources:
        - directory:
            exclude: '{root.yaml}'
            jsonnet: {}
          path: .
          repoURL: https://github.com/akolpakova/demo-argocd.git
          targetRevision: testing-devex
    - deployStartedAt: '2025-12-04T15:49:53Z'
      deployedAt: '2025-12-04T15:49:53Z'
      id: 3
      initiatedBy:
        automated: true
      revisions:
        - 9b78f583ad9ec20c64cebb8d6f1c373c981ce538
      source:
        repoURL: ''
      sources:
        - directory:
            exclude: '{root.yaml}'
            jsonnet: {}
          path: .
          repoURL: https://github.com/akolpakova/demo-argocd.git
          targetRevision: testing-devex
  operationState:
    finishedAt: '2025-12-04T17:11:50Z'
    message: >-
      one or more objects failed to apply, reason: error when patching
      "/dev/shm/3241259785": ApplicationSet.argoproj.io "clusters" is invalid:
      spec.generators: Required value (retried 5 times).
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        prune: true
        revisions:
          - 9b78f583ad9ec20c64cebb8d6f1c373c981ce538
          - 9b78f583ad9ec20c64cebb8d6f1c373c981ce538
        sources:
          - helm:
              valueFiles:
                - $values/argocd-production/config.yaml
                - $values/clusters/clusters-list.yaml
            path: renderers/clusters
            repoURL: https://github.com/akolpakova/demo-argocd.git
            targetRevision: testing-devex
          - ref: values
            repoURL: https://github.com/akolpakova/demo-argocd.git
            targetRevision: testing-devex
        syncOptions:
          - CreateNamespace=true
    phase: Failed
    retryCount: 5
    startedAt: '2025-12-04T17:06:40Z'
    syncResult:
      resources:
        - group: argoproj.io
          hookPhase: Failed
          kind: ApplicationSet
          message: >-
            error when patching "/dev/shm/3241259785":
            ApplicationSet.argoproj.io "clusters" is invalid: spec.generators:
            Required value
          name: clusters
          namespace: argocd
          status: SyncFailed
          syncPhase: Sync
          version: v1alpha1
      revision: ''
      revisions:
        - 9b78f583ad9ec20c64cebb8d6f1c373c981ce538
        - 9b78f583ad9ec20c64cebb8d6f1c373c981ce538
      source:
        repoURL: ''
      sources:
        - helm:
            valueFiles:
              - $values/argocd-production/config.yaml
              - $values/clusters/clusters-list.yaml
          path: renderers/clusters
          repoURL: https://github.com/akolpakova/demo-argocd.git
          targetRevision: testing-devex
        - ref: values
          repoURL: https://github.com/akolpakova/demo-argocd.git
          targetRevision: testing-devex
  reconciledAt: '2025-12-05T10:10:42Z'
  resourceHealthSource: appTree
  resources:
    - group: argoproj.io
      kind: ApplicationSet
      name: clusters
      namespace: argocd
      status: OutOfSync
      version: v1alpha1
  sourceHydrator: {}
  sourceTypes:
    - Helm
    - ''
  summary: {}
  sync:
    comparedTo:
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      ignoreDifferences:
        - group: argoproj.io
          jsonPointers:
            - /status
          kind: Application
      source:
        repoURL: ''
      sources:
        - helm:
            valueFiles:
              - $values/argocd-production/config.yaml
              - $values/clusters/clusters-list.yaml
          path: renderers/clusters
          repoURL: https://github.com/akolpakova/demo-argocd.git
          targetRevision: testing-devex
        - ref: values
          repoURL: https://github.com/akolpakova/demo-argocd.git
          targetRevision: testing-devex
    revisions:
      - 9b78f583ad9ec20c64cebb8d6f1c373c981ce538
      - 9b78f583ad9ec20c64cebb8d6f1c373c981ce538
    status: OutOfSync
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /status
      kind: Application
  project: default
  sources:
    - helm:
        valueFiles:
          - $values/argocd-production/config.yaml
          - $values/clusters/clusters-list.yaml
      path: renderers/clusters
      repoURL: https://github.com/akolpakova/demo-argocd.git
      targetRevision: testing-devex
    - ref: values
      repoURL: https://github.com/akolpakova/demo-argocd.git
      targetRevision: testing-devex
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
