apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/helm/examples.git
    targetRevision: main
    path: charts/hello-world
    helm:
      releaseName: hello-world-2
      values: |
        replicaCount: 3
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true