apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-first-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/helm/examples.git
    targetRevision: main
    path: charts/hello-world
    helm:
      releaseName: my-first-application
  destination:
    server: https://kubernetes.default.svc
    namespace: my-first-application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true